### ISSUE TITLE
大佬你好 我想知道 2018年的测试集 是在哪里下载的?

### ISSUE THREAD

**Issue by bringtree** [yuanxiaosc/SMP2018#1]

**Comment by bringtree** [comment]
求连接 readme里面那个 是17年的

**Comment by yuanxiaosc** [comment]
> 求连接 readme里面那个 是17年的

https://worksheets.codalab.org/worksheets/0x27203f932f8341b79841d50ce0fd684f/ ， 在这个数据链接里面我看到数据描述是 name: SMP2018-ECDT，说明数据应该是18年的。

**Comment by bringtree** [comment]
里面只有18年的训练集  🤦‍♀️
